openapi: "3.0.2"
info:
  version: 1.0.0
  title: Canonical Demo
  description: Multi-file boilerplate for OpenAPI Specification.
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://localhost:3000/v1
tags:
  - name: example
    description: Example placeholder apis
security:
- app_id: []
paths:
  /example:
    $ref: "./resources/example.yaml"
components:
  # parameters:
  #   $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  # responses:
  #   $ref: "./responses/_index.yaml"
  securitySchemes:
    app_id:
      type: apiKey
      description: API key to authorize requests.
      name: appid
      in: query